export const flagData = [
  {
    src: "/assets/FLAGS/Asexual.jpeg",
    title: "Asexual",
    alt: "Asexual Pride Flag",
    desc: "",
    reso: "",
  },
  {
    src: "/assets/FLAGS/Asexual.jpeg",
    title: "Bisexual",
    alt: "Asexual Pride Flag",
    desc: "",
    reso: "",
  },
  {
    src: "/assets/FLAGS/Asexual.jpeg",
    title: "Demisexual",
    alt: "Asexual Pride Flag",
    desc: "",
    reso: "",
  },
  {
    src: "/assets/FLAGS/Asexual.jpeg",
    title: "Gender Queer",
    alt: "Asexual Pride Flag",
    desc: "",
    reso: "",
  },
  {
    src: "/assets/FLAGS/Asexual.jpeg",
    title: "Intersex",
    alt: "Asexual Pride Flag",
    desc: "",
    reso: "",
  },
  {
    src: "/assets/FLAGS/Asexual.jpeg",
    title: "Lesbian",
    alt: "Asexual Pride Flag",
    desc: "",
    reso: "",
  },
  {
    src: "/assets/FLAGS/Asexual.jpeg",
    title: "Nonbinary",
    alt: "Asexual Pride Flag",
    desc: "",
    reso: "",
  },
  {
    src: "/assets/FLAGS/Asexual.jpeg",
    title: "Pansexual",
    alt: "Asexual Pride Flag",
    desc: "",
    reso: "",
  },
  {
    src: "/assets/FLAGS/Asexual.jpeg",
    title: "Polysexual",
    alt: "Asexual Pride Flag",
    desc: "",
    reso: "",
  },
  {
    src: "/assets/FLAGS/Asexual.jpeg",
    title: "QPOC",
    alt: "Asexual Pride Flag",
    desc: "",
    reso: "",
  },
  {
    src: "/assets/FLAGS/Asexual.jpeg",
    title: "Gay",
    alt: "Asexual Pride Flag",
    desc: "",
    reso: "",
  },
  {
    src: "/assets/FLAGS/Asexual.jpeg",
    title: "Transgender",
    alt: "Asexual Pride Flag",
    desc: "",
    reso: "",
  },
];
